### ISSUE TITLE
iOS 闪退

### ISSUE THREAD

**Issue by XIAZY** [beilunyang/otakuren#1]
用 Xcode 在真机部署了一下，闪退
问题好像出在这里
<img width="1392" alt="2016-10-01 11 18 58" src="https://cloud.githubusercontent.com/assets/8736607/19018411/71d86d3c-882d-11e6-805e-45ef81597dc3.png">
是我使用姿势不对？

**Comment by beilunyang** [comment]
是iOS10吗，在iOS10上确实会闪退╮(╯▽╰)╭

**Comment by XIAZY** [comment]
确实是 iOS 10……有办法解决吗？

**Comment by beilunyang** [comment]
将RN版本升到最新的0.34.0就不会闪退了，只不过会有新的错误╮(╯▽╰)╭。。。还是玩安卓吧

**Comment by XIAZY** [comment]
很惭愧，做了一点微小的工作。RN 是官网装的最新版，依然闪退。
是 Facebook 的锅？

**Comment by beilunyang** [comment]
已经更新到RN 0.34.0，没有出现闪退。请重新clone试试╮(╯▽╰)╭
![](http://ww3.sinaimg.cn/large/894a61a6gw1f8f52nlrb6j20ku12aqdi.jpg)

**Comment by XIAZY** [comment]
真机部署成功
![2ced8ff4-7b7f-4b63-9cb7-ce650db6b671](https://cloud.githubusercontent.com/assets/8736607/19059511/5f012dfc-89ae-11e6-90ec-f59f921e2004.PNG)

一个很奇怪的问题，打开时会卡在这个界面：
![d226ddb5-c26b-4958-9a5a-900272d7f89c](https://cloud.githubusercontent.com/assets/8736607/19059521/72295b70-89ae-11e6-861f-cd1d745db68e.PNG)

解决方法：
强退后重新开……

**Comment by XIAZY** [comment]
还有一个问题，阅读如果改成点触翻页体验会更好一些我觉得

**Comment by beilunyang** [comment]
会考虑改成点翻页的。。。
