### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by horizonl** [beilunyang/otakuren#2]
挂不挂梯子都是这样，Android端

**Comment by beilunyang** [comment]
API接口被封了╮(╯▽╰)╭

**Comment by horizonl** [comment]
有补救方法吗(ㆁωㆁ*)

**Comment by beilunyang** [comment]
以前抓的哔咔漫画1.0的包，现在哔咔漫画升级到了2.0，不知道用了什么方法，一抓包就无法成功请求数据╮(╯▽╰)╭。
